### ISSUE TITLE
Support BackupBatch in cli

### ISSUE THREAD

**Issue by tamalsaha** [stashed/stash#1037]

**Comment by codejamninja** [comment]
I was thinking the same thing. Right now I get the following error when I try and use the cli for BackupBatch.

```
Error: BackupConfiguration name not found
Usage:
  kubectl-stash trigger [flags]

Flags:
  -h, --help   help for trigger

Global Flags:
      --alsologtostderr                  log to standard error as well as files
      --as string                        Username to impersonate for the operation
      --as-group stringArray             Group to impersonate for the operation, this flag can be repeated to specify multiple groups.
      --cache-dir string                 Default HTTP cache directory (default "/home/codejamninja/.kube/http-cache")
      --certificate-authority string     Path to a cert file for the certificate authority
      --client-certificate string        Path to a client certificate file for TLS
      --client-key string                Path to a client key file for TLS
      --cluster string                   The name of the kubeconfig cluster to use
      --context string                   The name of the kubeconfig context to use
      --enable-analytics                 Send analytical events to Google Analytics (default true)
      --insecure-skip-tls-verify         If true, the server's certificate will not be checked for validity. This will make your HTTPS connections insecure
      --kubeconfig string                Path to the kubeconfig file to use for CLI requests.
      --log-backtrace-at traceLocation   when logging hits line file:N, emit a stack trace (default :0)
      --log-dir string                   If non-empty, write log files in this directory
      --log-flush-frequency duration     Maximum number of seconds between log flushes (default 5s)
      --logtostderr                      log to standard error instead of files
      --match-server-version             Require server version to match client version
  -n, --namespace string                 If present, the namespace scope for this CLI request
      --request-timeout string           The length of time to wait before giving up on a single server request. Non-zero values should contain a corresponding time unit (e.g. 1s, 2m, 3h). A value of zero means don't timeout requests. (default "0")
  -s, --server string                    The address and port of the Kubernetes API server
      --stderrthreshold severity         logs at or above this threshold go to stderr
      --token string                     Bearer token for authentication to the API server
      --use-kubeapiserver-fqdn-for-aks   if true, uses kube-apiserver FQDN for AKS cluster to workaround https://github.com/Azure/AKS/issues/522 (default true)
      --user string                      The name of the kubeconfig user to use
  -v, --v Level                          log level for V logs
      --vmodule moduleSpec               comma-separated list of pattern=N settings for file-filtered logging

F0125 05:53:38.742107   15162 main.go:43] error: BackupConfiguration name not found
goroutine 1 [running]:
github.com/golang/glog.stacks(0xc0009d7200, 0xc00043b1e0, 0x54, 0xaa)
	/src/vendor/github.com/golang/glog/glog.go:769 +0xb1
github.com/golang/glog.(*loggingT).output(0x2ba3580, 0xc000000003, 0xc000273180, 0x2af230e, 0x7, 0x2b, 0x0)
	/src/vendor/github.com/golang/glog/glog.go:720 +0x2f6
github.com/golang/glog.(*loggingT).printDepth(0x2ba3580, 0x3, 0x1, 0xc000231f28, 0x1, 0x1)
	/src/vendor/github.com/golang/glog/glog.go:646 +0x12b
github.com/golang/glog.FatalDepth(...)
	/src/vendor/github.com/golang/glog/glog.go:1134
github.com/appscode/go/log.Fatalln(0xc000231f68, 0x2, 0x2)
	/src/vendor/github.com/appscode/go/log/log.go:21 +0xb7
main.main()
	/src/cmd/kubectl-stash/main.go:43 +0x140
```
