### ISSUE TITLE
invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by bclermont** [stashed/stash#1068]
I'm sorry I don't have a better stacktrace, this is the log of a deleted pod took from loki/grafana.

this is v0.9.0-rc.6 release of stash, a sidecar of a volume workload

```
2020-03-12T14:08:31.364528786+08:00 stderr F /src/vendor/kmodules.xyz/client-go/tools/queue/worker.go:53 +0x93
2020-03-12T14:08:31.364523463+08:00 stderr F created by kmodules.xyz/client-go/tools/queue.(*Worker).Run
2020-03-12T14:08:31.364518381+08:00 stderr F /src/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
2020-03-12T14:08:31.364513169+08:00 stderr F k8s.io/apimachinery/pkg/util/wait.Until(0xc0003b8640, 0x3b9aca00, 0xc0005c57a0)
2020-03-12T14:08:31.364507941+08:00 stderr F /src/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0xf8
2020-03-12T14:08:31.364502298+08:00 stderr F k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0003b8640, 0x3b9aca00, 0x0, 0xc00076df01, 0xc0005c57a0)
2020-03-12T14:08:31.364497215+08:00 stderr F /src/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x5e
2020-03-12T14:08:31.364492135+08:00 stderr F k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc0003b8640)
2020-03-12T14:08:31.364487178+08:00 stderr F /src/vendor/kmodules.xyz/client-go/tools/queue/worker.go:67 +0x2b
2020-03-12T14:08:31.364481815+08:00 stderr F kmodules.xyz/client-go/tools/queue.(*Worker).processQueue(0xc000239980)
2020-03-12T14:08:31.364476773+08:00 stderr F /src/vendor/kmodules.xyz/client-go/tools/queue/worker.go:84 +0x102
2020-03-12T14:08:31.364471452+08:00 stderr F kmodules.xyz/client-go/tools/queue.(*Worker).processNextEntry(0xc000239980, 0x43306558535a6900)
2020-03-12T14:08:31.364460434+08:00 stderr F /src/pkg/backup/backupsession.go:201 +0x445
2020-03-12T14:08:31.364454095+08:00 stderr F stash.appscode.dev/stash/pkg/backup.(*BackupSessionController).processBackupSession(0xc0000f7000, 0xc0008073e0, 0x21, 0xc000295fc0, 0xc000295c00)
2020-03-12T14:08:31.364444455+08:00 stderr F /src/pkg/backup/backupsession.go:474 +0x26a
2020-03-12T14:08:31.364438942+08:00 stderr F stash.appscode.dev/stash/pkg/backup.(*BackupSessionController).handleBackupSuccess(0xc0000f7000, 0xc000829ae0, 0x1b, 0xc0009d4510, 0x10, 0x0, 0x0, 0xc0009d4520, 0x5, 0xc0002e91a0, ...)
2020-03-12T14:08:31.364431595+08:00 stderr F /src/pkg/status/status.go:166 +0x65e
2020-03-12T14:08:31.364426417+08:00 stderr F stash.appscode.dev/stash/pkg/status.UpdateStatusOptions.UpdatePostBackupStatus(0xc0006ff000, 0x2af0ce0, 0xc000366f00, 0x2a91ba0, 0xc00017ccc0, 0xc000322fb8, 0x5, 0xc0009420e0, 0x17, 0xc000829ae0, ...)
2020-03-12T14:08:31.364421208+08:00 stderr F /src/vendor/stash.appscode.dev/apimachinery/pkg/restic/metrics.go:441 +0x7a6
2020-03-12T14:08:31.364416039+08:00 stderr F stash.appscode.dev/apimachinery/pkg/restic.(*MetricsOptions).SendBackupHostMetrics(0xc0009df270, 0xc0006ff000, 0xc0009d4510, 0x10, 0x0, 0x0, 0xc0009d4520, 0x5, 0xc0002e91a0, 0x57, ...)
2020-03-12T14:08:31.364410391+08:00 stderr F /src/vendor/stash.appscode.dev/apimachinery/pkg/restic/metrics.go:614 +0x20e
2020-03-12T14:08:31.364405298+08:00 stderr F stash.appscode.dev/apimachinery/pkg/restic.(*BackupMetrics).setValues(0xc0008e3430, 0x25531bc, 0x6, 0x2557627, 0x9, 0xc0001075e0, 0x1, 0x1, 0xc000ae22c0, 0xd, ...)
2020-03-12T14:08:31.364400127+08:00 stderr F /usr/local/go/src/runtime/panic.go:679 +0x1b2
2020-03-12T14:08:31.364395014+08:00 stderr F panic(0x220bc20, 0x3d9f490)
2020-03-12T14:08:31.364389407+08:00 stderr F /src/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:55 +0x105
2020-03-12T14:08:31.364384099+08:00 stderr F k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
2020-03-12T14:08:31.364378926+08:00 stderr F goroutine 133 [running]:
2020-03-12T14:08:31.364372765+08:00 stderr F
2020-03-12T14:08:31.364368043+08:00 stderr F [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x15c939e]
2020-03-12T14:08:31.364363049+08:00 stderr F panic: runtime error: invalid memory address or nil pointer dereference
2020-03-12T14:08:31.364358002+08:00 stderr F panic: runtime error: invalid memory address or nil pointer dereference [recovered]
2020-03-12T14:08:31.364352983+08:00 stderr F /src/vendor/kmodules.xyz/client-go/tools/queue/worker.go:53 +0x93
2020-03-12T14:08:31.364347924+08:00 stderr F created by kmodules.xyz/client-go/tools/queue.(*Worker).Run
2020-03-12T14:08:31.364342846+08:00 stderr F /src/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
2020-03-12T14:08:31.364337565+08:00 stderr F k8s.io/apimachinery/pkg/util/wait.Until(0xc0003b8640, 0x3b9aca00, 0xc0005c57a0)
2020-03-12T14:08:31.364331928+08:00 stderr F /src/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0xf8
2020-03-12T14:08:31.36432622+08:00 stderr F k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0003b8640, 0x3b9aca00, 0x0, 0xc00076df01, 0xc0005c57a0)
2020-03-12T14:08:31.36432105+08:00 stderr F /src/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x5e
2020-03-12T14:08:31.364315877+08:00 stderr F k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc0003b8640)
2020-03-12T14:08:31.364310412+08:00 stderr F /src/vendor/kmodules.xyz/client-go/tools/queue/worker.go:67 +0x2b
2020-03-12T14:08:31.364305203+08:00 stderr F kmodules.xyz/client-go/tools/queue.(*Worker).processQueue(0xc000239980)
2020-03-12T14:08:31.364299636+08:00 stderr F /src/vendor/kmodules.xyz/client-go/tools/queue/worker.go:84 +0x102
2020-03-12T14:08:31.364291917+08:00 stderr F kmodules.xyz/client-go/tools/queue.(*Worker).processNextEntry(0xc000239980, 0x43306558535a6900)
2020-03-12T14:08:31.364285976+08:00 stderr F /src/pkg/backup/backupsession.go:201 +0x445
2020-03-12T14:08:31.364269522+08:00 stderr F stash.appscode.dev/stash/pkg/backup.(*BackupSessionController).processBackupSession(0xc0000f7000, 0xc0008073e0, 0x21, 0xc000295fc0, 0xc000295c00)
2020-03-12T14:08:31.364263441+08:00 stderr F /src/pkg/backup/backupsession.go:474 +0x26a
2020-03-12T14:08:31.36425707+08:00 stderr F stash.appscode.dev/stash/pkg/backup.(*BackupSessionController).handleBackupSuccess(0xc0000f7000, 0xc000829ae0, 0x1b, 0xc0009d4510, 0x10, 0x0, 0x0, 0xc0009d4520, 0x5, 0xc0002e91a0, ...)
2020-03-12T14:08:31.364251268+08:00 stderr F /src/pkg/status/status.go:166 +0x65e
2020-03-12T14:08:31.364245199+08:00 stderr F stash.appscode.dev/stash/pkg/status.UpdateStatusOptions.UpdatePostBackupStatus(0xc0006ff000, 0x2af0ce0, 0xc000366f00, 0x2a91ba0, 0xc00017ccc0, 0xc000322fb8, 0x5, 0xc0009420e0, 0x17, 0xc000829ae0, ...)
2020-03-12T14:08:31.364239292+08:00 stderr F /src/vendor/stash.appscode.dev/apimachinery/pkg/restic/metrics.go:441 +0x7a6
2020-03-12T14:08:31.364233419+08:00 stderr F stash.appscode.dev/apimachinery/pkg/restic.(*MetricsOptions).SendBackupHostMetrics(0xc0009df270, 0xc0006ff000, 0xc0009d4510, 0x10, 0x0, 0x0, 0xc0009d4520, 0x5, 0xc0002e91a0, 0x57, ...)
2020-03-12T14:08:31.364226724+08:00 stderr F /src/vendor/stash.appscode.dev/apimachinery/pkg/restic/metrics.go:614 +0x20e
2020-03-12T14:08:31.364214884+08:00 stderr F stash.appscode.dev/apimachinery/pkg/restic.(*BackupMetrics).setValues(0xc0008e3430, 0x25531bc, 0x6, 0x2557627, 0x9, 0xc0001075e0, 0x1, 0x1, 0xc000ae22c0, 0xd, ...)
2020-03-12T14:08:31.364208716+08:00 stderr F /usr/local/go/src/runtime/panic.go:679 +0x1b2
2020-03-12T14:08:31.364202679+08:00 stderr F panic(0x220bc20, 0x3d9f490)
2020-03-12T14:08:31.364196876+08:00 stderr F /src/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x82
2020-03-12T14:08:31.364190952+08:00 stderr F k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
2020-03-12T14:08:31.364184702+08:00 stderr F /src/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0xa3
2020-03-12T14:08:31.36417675+08:00 stderr F k8s.io/apimachinery/pkg/util/runtime.logPanic(0x220bc20, 0x3d9f490)
2020-03-12T14:08:31.364167715+08:00 stderr F goroutine 133 [running]:
2020-03-12T14:08:31.364134899+08:00 stderr F E0312 06:08:31.361545 1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
```

**Comment by hossainemruz** [comment]
@bclermont Can you please give the YAML of respective `BackupSession`. Seems like some conversion error.

**Comment by bclermont** [comment]
this is the obj right now, not sure it was the value during the time of the panic

```yaml
apiVersion: stash.appscode.com/v1beta1
kind: BackupSession
metadata:
  creationTimestamp: "2020-03-12T06:08:05Z"
  generation: 1
  labels:
    app: robotinfra-minio
    app.kubernetes.io/component: stash-backup
    app.kubernetes.io/managed-by: stash.appscode.com
    argocd.argoproj.io/instance: robotinfra-minio
    chart: minio-0.1.4
    heritage: Tiller
    release: robotinfra-minio
    stash.appscode.com/invoker-name: robotinfra-minio
    stash.appscode.com/invoker-type: BackupConfiguration
  name: robotinfra-minio-1583993285
  namespace: minio
  ownerReferences:
  - apiVersion: stash.appscode.com/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: BackupConfiguration
    name: robotinfra-minio
    uid: 146ace61-e88f-4d0a-a64d-62c808dc6262
  resourceVersion: "926218"
  selfLink: /apis/stash.appscode.com/v1beta1/namespaces/minio/backupsessions/robotinfra-minio-1583993285
  uid: 9c61c591-bb4e-4cf2-abdd-3722c746e00f
spec:
  invoker:
    apiGroup: stash.appscode.com
    kind: BackupConfiguration
    name: robotinfra-minio
status:
  phase: Succeeded
  sessionDuration: 26.326272424s
  targets:
  - phase: Succeeded
    ref:
      kind: Deployment
      name: robotinfra-minio
    stats:
    - duration: 24.763349097s
      hostname: host-0
      phase: Succeeded
      snapshots:
      - fileStats: {}
        path: /export
        processingTime: "0:00"
        totalSize: 0 B
        uploaded: 0 B
    totalHosts: 1
```

**Comment by hossainemruz** [comment]
Interesting. It seems something wrong with `/export` path. Can you give log from stash sidecar container? Also, if it is possible please give the YAML of the respective StatefulSet and BackupConfiguration.

**Comment by bclermont** [comment]
I reinstalled my cluster a few times and never been able to reproduce this, close
