### ISSUE TITLE
ElasticSearch Backup -  invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by underscoredje** [stashed/stash#1143]
I've got this error when trying to backup an ES 6.2.4.

Here is the backtrace:
```
I0630 15:12:39.445511       1 log.go:172] FLAG: --alsologtostderr="false"
I0630 15:12:39.445617       1 log.go:172] FLAG: --appbinding="elasticsearch-logging"
I0630 15:12:39.445635       1 log.go:172] FLAG: --bucket="stash-demo"
I0630 15:12:39.445645       1 log.go:172] FLAG: --enable-analytics="true"
I0630 15:12:39.445679       1 log.go:172] FLAG: --enable-cache="true"
I0630 15:12:39.445695       1 log.go:172] FLAG: --endpoint="http://minio.velero:9000"
I0630 15:12:39.445703       1 log.go:172] FLAG: --es-args=""
I0630 15:12:39.445716       1 log.go:172] FLAG: --help="false"
I0630 15:12:39.445737       1 log.go:172] FLAG: --hostname="host-0"
I0630 15:12:39.445760       1 log.go:172] FLAG: --interim-data-dir="/stash-interim-volume/data"
I0630 15:12:39.445774       1 log.go:172] FLAG: --kubeconfig=""
I0630 15:12:39.445783       1 log.go:172] FLAG: --log-flush-frequency="5s"
I0630 15:12:39.445798       1 log.go:172] FLAG: --log_backtrace_at=":0"
I0630 15:12:39.445822       1 log.go:172] FLAG: --log_dir=""
I0630 15:12:39.445830       1 log.go:172] FLAG: --logtostderr="true"
I0630 15:12:39.445838       1 log.go:172] FLAG: --master=""
I0630 15:12:39.445848       1 log.go:172] FLAG: --max-connections="0"
I0630 15:12:39.445860       1 log.go:172] FLAG: --namespace="ntnx-system"
I0630 15:12:39.445869       1 log.go:172] FLAG: --output-dir="/tmp/output"
I0630 15:12:39.445878       1 log.go:172] FLAG: --path="/elasticsearch-logging"
I0630 15:12:39.445899       1 log.go:172] FLAG: --provider="s3"
I0630 15:12:39.445912       1 log.go:172] FLAG: --region=""
I0630 15:12:39.445921       1 log.go:172] FLAG: --retention-dry-run="false"
I0630 15:12:39.445929       1 log.go:172] FLAG: --retention-keep-daily="0"
I0630 15:12:39.445944       1 log.go:172] FLAG: --retention-keep-hourly="0"
I0630 15:12:39.445953       1 log.go:172] FLAG: --retention-keep-last="5"
I0630 15:12:39.445963       1 log.go:172] FLAG: --retention-keep-monthly="0"
I0630 15:12:39.445983       1 log.go:172] FLAG: --retention-keep-tags="[]"
I0630 15:12:39.445995       1 log.go:172] FLAG: --retention-keep-weekly="0"
I0630 15:12:39.446007       1 log.go:172] FLAG: --retention-keep-yearly="0"
I0630 15:12:39.446016       1 log.go:172] FLAG: --retention-prune="true"
I0630 15:12:39.446029       1 log.go:172] FLAG: --scratch-dir="/tmp"
I0630 15:12:39.446038       1 log.go:172] FLAG: --secret-dir="***REDACTED***"
I0630 15:12:39.446047       1 log.go:172] FLAG: --service-name="stash-operator"
I0630 15:12:39.446062       1 log.go:172] FLAG: --stderrthreshold="0"
I0630 15:12:39.446071       1 log.go:172] FLAG: --v="0"
I0630 15:12:39.446080       1 log.go:172] FLAG: --vmodule=""
W0630 15:12:44.604516       1 client_config.go:541] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x130af70]
goroutine 1 [running]:
stash.appscode.dev/elasticsearch/pkg.(*esOptions).backupElasticsearch(0xc00019cb40, 0xc000747c70, 0x0, 0x0)
	/src/pkg/backup.go:152 +0x1c0
stash.appscode.dev/elasticsearch/pkg.NewCmdBackup.func1(0xc000392c80, 0xc000311200, 0x0, 0x18, 0x0, 0x0)
	/src/pkg/backup.go:79 +0x198
github.com/spf13/cobra.(*Command).execute(0xc000392c80, 0xc000311080, 0x18, 0x18, 0xc000392c80, 0xc000311080)
	/src/vendor/github.com/spf13/cobra/command.go:826 +0x460
github.com/spf13/cobra.(*Command).ExecuteC(0xc00026d900, 0x4, 0x0, 0x0)
	/src/vendor/github.com/spf13/cobra/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
	/src/vendor/github.com/spf13/cobra/command.go:864
main.main()
	/src/cmd/stash-elasticsearch/main.go:40 +0x7b
```

Looking at elasticsearch//src/pkg/backup.go:152, seems it doesn't retrieve appbinding.

Here is AppBinding and BackupConfiguration
```
apiVersion: appcatalog.appscode.com/v1alpha1
kind: AppBinding
metadata:
  annotations:
  name: elasticsearch-logging
  namespace: ntnx-system
spec:
  clientConfig:
    service:
      name: elasticsearch-logging
      port: 9200
      scheme: http
  type: kubedb.com/elasticsearch
  version: 6.2.4


---

apiVersion: v1
items:
- apiVersion: stash.appscode.com/v1beta1
  kind: BackupConfiguration
  metadata:
    finalizers:
    - stash.appscode.com
    generation: 5
    name: elasticsearch-logging-backup
    namespace: ntnx-system
  spec:
    interimVolumeTemplate:
      metadata:
        name: stash-tmp-storage
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 80Gi
    repository:
      name: s3-repo
    retentionPolicy:
      keepLast: 5
      name: keep-last-5
      prune: true
    schedule: 0 22 * * *
    target:
      ref:
        apiVersion: appcatalog.appscode.com/v1alpha1
        kind: AppBinding
        name: elasticsearch-logging
    task:
      name: elasticsearch-backup-6.2.4

```

Am I doing something wrong ?

**Comment by hossainemruz** [comment]
Your `AppBinding` does not have secret field specified. Currently, Stash does not support backup of credential less  Elasticsearch. There error is coming from here:
https://github.com/stashed/elasticsearch/blob/41101dd1bc702e5222d0b152e90ee7d27a00f48c/pkg/backup.go#L155

**Comment by underscoredje** [comment]
OK, Thank you for the information.
