### ISSUE TITLE
Unable to install kubectl stash plugin on Apple Silicon (arm64)

### ISSUE THREAD

**Issue by timbrd** [stashed/stash#1408]
I have tried to install the kubectl stash plugin on my M1 Macbook Pro (arm64), but it seems that the plugin is available on amd64 only:

```
➜  ~ kubectl krew install appscode/stash

Updated the local copy of plugin index "appscode".
Installing plugin: stash
W1217 19:22:57.482144   81270 install.go:164] failed to install plugin "stash": plugin "stash" does not offer installation for this platform
F1217 19:22:57.482201   81270 root.go:79] failed to install some plugins: [stash]: plugin "stash" does not offer installation for this platform
goroutine 1 [running]:
k8s.io/klog/v2.stacks(0x1)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/k8s.io/klog/v2@v2.8.0/klog.go:1021 +0xac
k8s.io/klog/v2.(*loggingT).output(0x1015576c0, 0x3, {0x0, 0x0}, 0x1400052ae70, {0x1012763e3, 0x7}, 0x4f, 0x0)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/k8s.io/klog/v2@v2.8.0/klog.go:970 +0x588
k8s.io/klog/v2.(*loggingT).printDepth(0x1015576c0, 0x3, {0x0, 0x0}, {0x0, 0x0}, 0x1, {0x1400052e730, 0x1, 0x1})
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/k8s.io/klog/v2@v2.8.0/klog.go:733 +0x1ac
k8s.io/klog/v2.(*loggingT).print(...)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/k8s.io/klog/v2@v2.8.0/klog.go:715
k8s.io/klog/v2.Fatal(...)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/k8s.io/klog/v2@v2.8.0/klog.go:1489
sigs.k8s.io/krew/cmd/krew/cmd.Execute()
	/private/tmp/krew-20211024-22302-196yo0l/cmd/krew/cmd/root.go:79 +0x228
main.main()
	/private/tmp/krew-20211024-22302-196yo0l/cmd/krew/main.go:25 +0x3c

goroutine 18 [chan receive]:
k8s.io/klog/v2.(*loggingT).flushDaemon(0x1015576c0)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/k8s.io/klog/v2@v2.8.0/klog.go:1164 +0x70
created by k8s.io/klog/v2.init.0
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/k8s.io/klog/v2@v2.8.0/klog.go:418 +0x150
[...]
```

**Comment by hossainemruz** [comment]
@timbrd we haven't published ARM binary for Mac yet.

**Comment by timbrd** [comment]
@hossainemruz Thanks for clarification. Since the plugin is written in Go, is there a documentation on how to build the plugin? It should be quite simple to compile it for ARM.

**Comment by timbrd** [comment]
Nevermind, I found the '[documentation](https://stash.run/docs/v2021.11.24/setup/install/kubectl_plugin/)'. I'll try to build the plugin for ARM.

**Comment by hossainemruz** [comment]
Should be fixed by https://github.com/stashed/cli/pull/149.
