### ISSUE TITLE
Stash restore job fails

### ISSUE THREAD

**Issue by codejamninja** [stashed/stash#914]
I am getting the following error when running a stash restore job

```
I1005 07:27:56.753793       1 log.go:172] FLAG: --alsologtostderr="false"
I1005 07:27:56.754026       1 log.go:172] FLAG: --appbinding="gitlab-4jfsm-gitlab-postgres"
I1005 07:27:56.754104       1 log.go:172] FLAG: --bucket="codejamninja-backups"
I1005 07:27:56.754156       1 log.go:172] FLAG: --enable-analytics="true"
I1005 07:27:56.754179       1 log.go:172] FLAG: --enable-cache="true"
I1005 07:27:56.754218       1 log.go:172] FLAG: --enable-status-subresource="false"
I1005 07:27:56.754274       1 log.go:172] FLAG: --endpoint="s3.amazonaws.com"
I1005 07:27:56.754322       1 log.go:172] FLAG: --help="false"
I1005 07:27:56.754360       1 log.go:172] FLAG: --hostname="host-0"
I1005 07:27:56.754394       1 log.go:172] FLAG: --kubeconfig=""
I1005 07:27:56.754442       1 log.go:172] FLAG: --log-flush-frequency="5s"
I1005 07:27:56.754492       1 log.go:172] FLAG: --log_backtrace_at=":0"
I1005 07:27:56.754534       1 log.go:172] FLAG: --log_dir=""
I1005 07:27:56.754573       1 log.go:172] FLAG: --logtostderr="true"
I1005 07:27:56.754824       1 log.go:172] FLAG: --master=""
I1005 07:27:56.754833       1 log.go:172] FLAG: --max-connections="0"
I1005 07:27:56.754840       1 log.go:172] FLAG: --namespace="gitlab"
I1005 07:27:56.754847       1 log.go:172] FLAG: --output-dir="/tmp/output"
I1005 07:27:56.754854       1 log.go:172] FLAG: --path="/gitlab/postgres"
I1005 07:27:56.754860       1 log.go:172] FLAG: --pg-args=""
I1005 07:27:56.754867       1 log.go:172] FLAG: --provider="s3"
I1005 07:27:56.754878       1 log.go:172] FLAG: --scratch-dir="/tmp"
I1005 07:27:56.754885       1 log.go:172] FLAG: --secret-dir="***REDACTED***"
I1005 07:27:56.754911       1 log.go:172] FLAG: --service-name="stash-operator"
I1005 07:27:56.754919       1 log.go:172] FLAG: --snapshot="1a6c1aa0"
I1005 07:27:56.754926       1 log.go:172] FLAG: --source-hostname="host-0"
I1005 07:27:56.754933       1 log.go:172] FLAG: --stderrthreshold="0"
I1005 07:27:56.754940       1 log.go:172] FLAG: --use-kubeapiserver-fqdn-for-aks="true"
I1005 07:27:56.754994       1 log.go:172] FLAG: --v="0"
I1005 07:27:56.755003       1 log.go:172] FLAG: --vmodule=""
W1005 07:28:01.863585       1 client_config.go:549] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x150d9e0]
goroutine 1 [running]:
stash.appscode.dev/postgres/pkg.(*postgresOptions).restorePostgreSQL(0xc0003a0fc0, 0xc0007258c0, 0x0, 0x0)
	/src/pkg/restore.go:119 +0x1c0
stash.appscode.dev/postgres/pkg.NewCmdRestore.func1(0xc0003fd400, 0xc0004900f0, 0x0, 0xf, 0x0, 0x0)
	/src/pkg/restore.go:55 +0x185
github.com/spf13/cobra.(*Command).execute(0xc0003fd400, 0xc000490000, 0xf, 0xf, 0xc0003fd400, 0xc000490000)
	/src/vendor/github.com/spf13/cobra/command.go:826 +0x465
github.com/spf13/cobra.(*Command).ExecuteC(0xc0003fcc80, 0x2, 0x0, 0x0)
	/src/vendor/github.com/spf13/cobra/command.go:914 +0x2fc
github.com/spf13/cobra.(*Command).Execute(...)
	/src/vendor/github.com/spf13/cobra/command.go:864
main.main()
	/src/cmd/stash-postgres/main.go:23 +0x72
```

**Comment by codejamninja** [comment]
This was a configuration on my end. I was referencing an incorrect repository.
